apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: null
  name: releaser-sample-v0.0.9
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/linuxsuren-bot/linuxsuren-releaser
      branch: master
      name: test
  phase: done
  repositories:
  - action: release
    address: https://github.com/linuxsuren-bot/test
    branch: master
    name: test
    version: v0.0.9
  secret:
    name: test-git
    namespace: default
  version: v0.0.9
status: {}
