apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: null
  name: releaser-sample-4
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/linuxsuren-bot/linuxsuren-releaser
      branch: master
      name: test
  phase: draft
  repositories:
  - action: release
    address: https://github.com/linuxsuren-bot/test
    branch: master
    name: test
    version: v0.0.7
  secret:
    name: test-git
    namespace: default
  version: v0.0.7
status: {}
